//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCStock.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProduct()
        {
            this.tblSale = new HashSet<tblSale>();
        }
    
        public int ProductID { get; set; }

        //[Required(ErrorMessage = "Ürün Adı Boş Bırakılamaz")]
        //[StringLength(50, ErrorMessage = "En Fazla 50 Karakter Girilebilir...")]
        public string ProductName { get; set; }

        //[Required(ErrorMessage = "Marka Bilgisi Boş Bırakılamaz")]
        //[StringLength(50, ErrorMessage = "En Fazla 50 Karakter Girilebilir...")]
        public string ProductBrand { get; set; }

        public Nullable<short> ProductCategory { get; set; }

        //[Required(ErrorMessage = "Fiyat Bilgisi Boş Bırakılamaz")]
        //[Range(0, 250000, ErrorMessage = "Fiyat (0,250.000) aralığında olmalı...")]
        public Nullable<decimal> ProductPrice { get; set; }

        //[Required(ErrorMessage = "Stok Bilgisi Boş Bırakılamaz")]
        //[Range(0, 2000000000, ErrorMessage = "Stok (0,2.000.000.000) aralığında olmalı...")]
        public Nullable<int> ProductStock { get; set; }
    
        public virtual tblCategory tblCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSale> tblSale { get; set; }
    }
}
